import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "node:path";
import fs from "node:fs";

// Plain Vite + React SPA — no TanStack Start, no server functions. All data
// access goes through src/lib/apiClient.ts to the separate backend/ API.

// ---------------------------------------------------------------------------
// Tailwind content-scanning workaround (Windows-only failure mode)
// ---------------------------------------------------------------------------
// This machine's Application Control (WDAC) policy blocks the native
// @tailwindcss/oxide .node binary from loading at all (ERR_DLOPEN_FAILED —
// see the README's "Windows note"), which is why NAPI_RS_FORCE_WASI=true
// forces the WASM fallback. That WASM binding *loads* fine, but its
// filesystem scanner silently returns zero matches on this box: both
// `Scanner.scan()` (glob-based directory walk) and `Scanner.scanFiles()`
// (explicit file path) return `[]` even for a real file with obvious
// Tailwind classes in it — almost certainly Node's experimental WASI
// preopens failing to enumerate directories on Windows. Passing candidates
// straight into the compiler (bypassing the scanner) works correctly, which
// is what this plugin does: it finds class-like tokens itself with plain
// Node `fs` (unaffected by either the native-binary block or the WASM
// scanner bug) and feeds them to Tailwind via the `@source inline(...)`
// directive — a supported v4 escape hatch for literal candidates that never
// touches the filesystem scanner. `src/styles.css` sets `source(none)` and
// `@import`s the file this plugin (re)writes on every relevant change.
//
// Extraction is deliberately scoped to *string-literal contents* inside
// .tsx/.jsx (not whole raw file bytes the way Tailwind's own v3-era
// extractor did) — an earlier version of this scanned every non-whitespace
// token in every source file and produced ~12k candidates (import paths,
// prose, identifiers...), which crashed the dev server with a JS heap OOM
// while Tailwind tried to compile all of them. classNames only ever live
// inside quoted/template strings, so scoping to those keeps the candidate
// set small and accurate.
const SRC_DIR = path.resolve(__dirname, "./src");
const GENERATED_CSS = path.resolve(SRC_DIR, "tw-safelist.generated.css");
const SCAN_EXTENSIONS = new Set([".tsx", ".jsx"]);
const STRING_LITERAL_RE = /"([^"\n]*)"|'([^'\n]*)'|`([^`]*)`/g;
const CLASS_TOKEN_RE = /^[a-zA-Z0-9_](?:[a-zA-Z0-9_\-:/.[\]%!#(),]){0,80}$/;

function collectFiles(dir: string, out: string[]) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "dist") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) collectFiles(full, out);
    else if (SCAN_EXTENSIONS.has(path.extname(entry.name))) out.push(full);
  }
}

function scanCandidates(): string {
  const files: string[] = [];
  collectFiles(SRC_DIR, files);
  const candidates = new Set<string>();
  for (const file of files) {
    const text = fs.readFileSync(file, "utf8");
    for (const strMatch of text.matchAll(STRING_LITERAL_RE)) {
      const literal = strMatch[1] ?? strMatch[2] ?? strMatch[3] ?? "";
      for (const token of literal.split(/\s+/)) {
        if (token && CLASS_TOKEN_RE.test(token)) candidates.add(token);
      }
    }
  }
  return Array.from(candidates).sort().join(" ");
}

function writeGeneratedSources() {
  const list = scanCandidates();
  const content = `/* AUTO-GENERATED by the tailwind-safelist-scan Vite plugin (vite.config.ts) — do not edit by hand.\n   Regenerated on every .tsx/.jsx add/change/delete. See the comment in vite.config.ts for why this file exists. */\n@source inline("${list}");\n`;
  fs.writeFileSync(GENERATED_CSS, content);
}

function tailwindSafelistScan() {
  let timer: ReturnType<typeof setTimeout> | undefined;
  return {
    name: "tailwind-safelist-scan",
    configResolved() {
      writeGeneratedSources();
    },
    configureServer(server: import("vite").ViteDevServer) {
      const rescan = (file: string) => {
        if (path.resolve(file) === GENERATED_CSS) return;
        if (!SCAN_EXTENSIONS.has(path.extname(file))) return;
        clearTimeout(timer);
        timer = setTimeout(writeGeneratedSources, 150);
      };
      server.watcher.on("add", rescan);
      server.watcher.on("change", rescan);
      server.watcher.on("unlink", rescan);
    },
  };
}

export default defineConfig({
  plugins: [tailwindSafelistScan(), react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 5173,
  },
});
